### PR TITLE
Add section about limitations and how to apply workarounds

### PR DESCRIPTION
**Pull request by AJenbo**
These are notes based on issue and solutions from when I was getting the project I work on to be fully processed.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the detailed info about weak parts.

Those should be handled by the compiler, as the context is known and we should handle it for the user instead to privde the best user experience possible :)

**Comment by AJenbo** [comment]
> Those should be handled by the compiler, as the context is known and we should handle it for the user instead to privde the best user experience possible :)

I much agree, but solving this will take some work so I'm thinking this would be useful for early adopters :)

**Comment by TomasVotruba** [comment]
Indeed. It would also state it's the intended and lead us astray from solution :)

Could you share a reproducible test case instead?

**Comment by AJenbo** [comment]
Turns out the first case isn't actually an issue, but I was getting misleading error message because of an issue with how includes where being processed. That one is now fixed in #52, and I created a test case for the other one in #54

**Pull request closed without merging**
