### PR TITLE
Test for including empty content

### PR DESCRIPTION
**Pull request by AJenbo**
Add test for https://github.com/TomasVotruba/bladestan/issues/42

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider adding a test for totally empty files.

**Comment by AJenbo** [comment]
Oh, I actually did it that way initially but thought it would be more meaning full/realistic to have a file with some static content. Should add another file or just empty the file?

**Comment by szepeviktor** [comment]
Another one.

**Comment by AJenbo** [comment]
Done

**Comment by TomasVotruba** [comment]
Thanks :partying_face:

**Comment by TomasVotruba** [comment]
I'll fix the line conflict in test manually :+1:

**Comment by AJenbo** [comment]
Ok, hope you can also look at #52 as that is what's going to bring home the bagels for me :D

**Comment by TomasVotruba** [comment]
I'm on it :)

**Pull request merged**
